#!/bin/sh

lock() {
    i3lock -c 000000 -e -f

    (while true
    do
        sleep 10
        if pgrep i3lock
	then
	  blackout
	else
	  break
	fi
    done) &
}

blackout() {
    xset dpms force off
}

case "$1" in
    lock)
        lock
        ;;
    blackout)
        blackout
	;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && systemctl suspend
        ;;
    hibernate)
        lock && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
        ;;
esac

exit 0
